version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
      MYSQL_USER: aziz
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - achat_network
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: neysho/achat-backend:1
    container_name: achat_backend
    ports:
      - "8082:8082"
    networks:
      - achat_network
    depends_on:
      - mysql

  frontend:
    image: neysho/achat-frontend:1
    container_name: achat_frontend
    ports:
      - "4200:80"
    networks:
      - achat_network
    depends_on:
      - backend    

networks:
  achat_network:
    driver: bridge

volumes:
  mysql_data:
